#%RAML 0.8
title: RxSearcher
version: v1
documentation:
  - title: RxSearcher
    content: API for the rxsearcher api-server reimplementation.
baseUri: http://rxsearch.herokuapp.com
schemas:
  - results: !include schemas/result.schema
/search/offers:
  description: Search for offers
  displayName: Search offers
  get:
    queryParameters:
      q:
        type: string
        required: true
        description: Keyword parameter
    headers:
      X-Request-ID:
        type: string
        required: false
        description: Request id
    description: Search for offers via get request
    responses:
      200:
        headers:
          x-response-time:
            type: string
            description: The time the request took
        description: A successful response
        body:
          application/json:
            schema: results
            example: |
              {
                "results" : [
                  {
                    "url": "http://www.zoom.com.br/lead?oid=17277895&sortorder=-1&index=&searchterm=&pagesize=&channel=12&og=19164&utm_source=foxy_deal&utm_medium=parceiros&utm_term=Celular+e+Smartphone&utm_campaign=Acess%C3%B3riosapple+%26+Mult&utm_content=iPhone+6+16GB+Apple+Cinza+Espacial",
                    "title": "iPhone 6 16GB Apple Cinza Espacial",
                    "price": {
                        "amount":345.12,
                        "currency":"BRL"
                    },
                    "searcher":"zoom",
                    "image": "http://i3.zst.com.br/thumbs/8/20/11/48683844.jpg",
                    "category": "Celular e Smartphone",
                    "merchant": {
                        "id": "3541",
                        "name": "Acessóriosapple & Mult",
                        "image": "http://i4.zst.com.br/thumbs/46/30/3e/50806552.jpg",
                        "category": "null"
                    },
                    "description": "O iPhone 6 é o smartphone da Apple lançado em setembro de 2014 rodando o sistema operacional iOS 8. O aparelho possui uma tela de 4,7 polegadas HD Retina com 1334 x 750 pixels de resolução, com 326 ppi. O dispositivo tem 6,8 mm de espessura e possui um processador A8 com 64 bits e um coprocessador M8. A câmera traseira do iPhone é de 8...",
                    "brand": "Apple",
                    "manufacturer": "Apple",
                    "originalUrl": "some_url",
                    "shippingCosts" : {
                        "amount":3.00,
                        "currency":"BRL"
                    }
                  }
                ]
              }
      204:
        headers:
          x-response-time:
            type: string
            description: The time the request took
        description: No offers could be found for the query. Either all searchers timed out or were actually no offers found.
      408:
        headers:
          x-response-time:
            type: string
            description: The time the request took
        description: The request took longer than six seconds and timed out. No response returned.

