#%RAML 1.0 Merchant
types:
  Merchant:
    type: object
    properties:
      name:
        type: string
        required: true
      image:
        type: string
        required: false
      id:
        type: string
        required: false
      category:
        type: string
        required: false
