#%RAML 1.0 Offer
type: object
properties:
  url:
    type: string
    required: true
  title:
    type: string
    required: true
  price:
    type: Money
    required: true
  searcher:
    type: string
    required: true
  image:
    type: string
    required: false
  category:
    type: string
    required: false
  merchant:
    type: Merchant
    required: false
  originalUrl:
    type: string
    required: false
  shippingCosts:
    type: Money
    required: false
  manufacturer:
    type: string
    required: false
  description:
    type: string
    required: false
  brand:
    type: string
    required: false